### ISSUE TITLE
XB-Config Wine Compatibility?

### ISSUE THREAD

**Issue by SeongGino** [Hipnosis183/XB-Monitor#2]
Hi! Just wanted to say that while the main XB-Loader itself seems to work just fine on Linux through Wine, the .NET based Configurator doesn't.

Either when using Wine's Mono or a real .NET 2.0 runtime or above, this is the error:
![2023_07-22 220126-Microsoft  NET Framework](https://github.com/Hipnosis183/XB-Monitor/assets/7321839/439e24ba-1167-41d9-ac3b-d4141a0e7b72)
(the error cuts out: it ends with "file not found")
The window itself does show fine, but the dropdown list (presumably to list available input devices) just shows nothing.

![2023_07-22 222145](https://github.com/Hipnosis183/XB-Monitor/assets/7321839/ee744596-fabd-47fd-9584-725841f3cfbf)

I understand if this might not mean a lot to you given how niche of a project this is, but any input on this matter would be appreciated!

**Comment by Hipnosis183** [comment]
Hey, just looked into it and it seems to be an issue with Wine's DirectX implementation, as other applications of similar nature also show similar problems.

To solve it you should install DirectX, but Wine's documentation recommends against that, so I included the required DirectInput libraries in the release page to make it easier. It should work with both Mono and .NET.

I don't have any games at hand to test if everything works correctly, so let me know if it does.

**Comment by SeongGino** [comment]
Thank you very much for the response! Indeed, providing the DLLs in the same directory as XB-Config.exe allows it to work.

...Sort of? Mono runtime definitely could run it, but after some indeterminate amount of time after it just started throwing the same errors? And I honest to goodness couldn't tell you why. I've since tried on a prefix with a native .NET 3.5 installed, and it seems to work as well *and stay working* for the moment.
Considering that it does fix the problem, I can only assume this might be something in Bottles maybe messing things up? Don't know, but the point is it works now.
___

On a small sidenote, I notice a touch more input lag with running eX-Board games with XB-Monitor+ versus their NESiCAxLive counterparts (using JConfig for Nesica) - or at least I noticed this with both versions of Suggoi! Arcana Heart 2.

**Comment by Hipnosis183** [comment]
Thanks for the confirmation, I'll update TTX-Monitor as well.

> On a small sidenote, I notice a touch more input lag with running eX-Board games with XB-Monitor+ versus their NESiCAxLive counterparts (using JConfig for Nesica) - or at least I noticed this with both versions of Suggoi! Arcana Heart 2.

XB-Monitor uses a 20ms delay in the polling thread to reduce processing, but at best it should be no more than a single frame of lag, assuming the game runs at 60 fps. The polling code is pretty simple, so I doubt it takes too long to execute (although I never actually tested how long it takes, it just felt about right). There are other variables that can play a role here, such as the OS, drivers and the games themselves (and in this case I guess Wine as well).

If you want you can try lowering the delay value [here](https://github.com/Hipnosis183/XB-Monitor/blob/master/XB-Monitor/SetInput.cpp#L368) to see if it changes something. I don't remember much since it's been three years, but to compile XB-Monitor (just the library, not the Config and Loader programs) you can use the default C compiler that comes with Visual Studio.

If you want to discuss the input lag problem further open a separate issue, as I'm closing this one.
